networks:
  proxy-network:
    external: true
  db-network:
    external: true
services:
  kumon:
    build:
      context: .
      dockerfile: dockerfile
    container_name: kumon
    user: ${UID}:${GID}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_KUMON}
      MYSQL_USER: ${MYSQL_USER_KUMON}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_KUMON}
      ROOT_DIR: ${ROOT_DIR}
      KUMON_DIR: ${KUMON_DIR}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
    volumes:
      - type: bind
        source: ./log
        target: /var/www/log
      - ./infra/www/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./infra/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./infra/php/kumon.logrotate:/etc/logrotate.d/kumon
      - ./app:/var/www/html
    networks:
      - proxy-network
      - db-network
